#!/usr/bin/env bash

ps cax | grep yabai > /dev/null
if [ $? -eq 0 ]; then
  RESULT=$(/usr/local/bin/yabai -m query --spaces --space)
  echo -e "$RESULT" | grep index | sed 's/[^0-9]*//g'
  if [ "$(echo "$RESULT" | /usr/local/bin/jq '.type')" == '"stack"' ]; then
    echo -e "≣"
  else
    echo -e "∷"
  fi
else
  echo ""
fi

